"""Linking shapa's git triggers into a repo without clobbering what is
already there.

A hook file has exactly one owner. Before writing anything, :func:`state`
reads what git actually does for a hook today: a machine-wide shared
``core.hooksPath`` (set at global or system scope, or pointing somewhere
outside this checkout entirely - another tool's convention for wiring every
repo on the box through one directory) must never be written into from
here; a hook manager (husky, lefthook, the ``pre-commit`` framework) owns
its hook file through its own config, so shapa prints the snippet to add
rather than fighting it for the file; a hand-written foreign hook is left
byte-identical, with the lines to paste in printed instead. Only a missing
or shapa-owned hook file is ever written, and only inside the repo's own
git common directory - :func:`install` never writes anywhere else.

``shapa ledger git-hooks`` is the direct CLI entry point (see
:mod:`shapa.ledger`, which re-exports the names below for backward
compatibility); ``shapa init`` calls :func:`install` too, so a wiki's
triggers are wired the moment the wiki exists.
"""

from __future__ import annotations

import subprocess
from pathlib import Path

GIT_TIMEOUT = 10

#: Marks a hook file as shapa's own, so a rerun can tell "ours" (safe to
#: rewrite) from "someone else's" (never touched).
GIT_HOOK_MARK = "# shapa ledger hook"
GIT_HOOKS = {
    "pre-commit": (f"#!/bin/sh\n{GIT_HOOK_MARK}: a wiki database commits only on the default "
                   "branch.\n# exit 1 is shapa's refusal; a missing or older shapa lets the "
                   "commit through.\nif command -v shapa >/dev/null 2>&1; then\n"
                   "\tshapa ledger pre-commit\n\t[ $? -eq 1 ] && exit 1\nfi\nexit 0\n"),
    "post-commit": (f"#!/bin/sh\n{GIT_HOOK_MARK}: a \"J<n>:\" commit subject closes that "
                    "job.\ncommand -v shapa >/dev/null 2>&1 && shapa ledger on-commit "
                    "2>/dev/null\nexit 0\n"),
}

#: The invocation each hook is expected to make - a hand-written hook that
#: already calls this counts as "wired" even without shapa's own marker.
HOOK_TRIGGER = {"pre-commit": "shapa ledger pre-commit", "post-commit": "shapa ledger on-commit"}

MANAGER_FILES = {
    "lefthook": ("lefthook.yml", ".lefthook.yml", "lefthook.yaml", ".lefthook.yaml"),
    "pre-commit": (".pre-commit-config.yaml",),
}


class CommandError(Exception):
    pass


# --- reading git's own view of the hooks dir --------------------------------------

def _git(cwd, *args, timeout=GIT_TIMEOUT) -> subprocess.CompletedProcess:
    return subprocess.run(["git", "-C", str(cwd), *args], capture_output=True, text=True,
                          timeout=timeout, check=False)


def _abs_path(repo, *args) -> Path | None:
    r = _git(repo, "rev-parse", "--path-format=absolute", *args)
    if r.returncode != 0 or not r.stdout.strip():
        return None
    return Path(r.stdout.strip())


def _hooks_dir(repo: Path) -> Path:
    found = _abs_path(repo, "--git-path", "hooks")
    if found is None:
        raise CommandError(f"{repo} is not a git checkout")
    return found


def _hooks_path_scope(repo: Path) -> tuple[str | None, str | None]:
    """``(scope, value)`` of ``core.hooksPath`` as git itself resolves it -
    ``(None, None)`` when it is unset."""
    r = _git(repo, "config", "--show-scope", "--get", "core.hooksPath")
    if r.returncode != 0 or not r.stdout.strip():
        return None, None
    scope, _, value = r.stdout.strip().partition("\t")
    return (scope or None), (value or None)


def _within(path: Path, *bases: Path | None) -> bool:
    try:
        rp = path.resolve()
    except OSError:
        rp = path
    for base in bases:
        if base is None:
            continue
        try:
            rb = base.resolve()
        except OSError:
            rb = base
        if rp == rb or rb in rp.parents:
            return True
    return False


def _detect_manager(top_level: Path | None, hooks_path_value: str | None,
                     hook_texts: dict[str, str]) -> str | None:
    top = top_level or Path.cwd()
    if (hooks_path_value and ".husky" in hooks_path_value) or (top / ".husky").is_dir():
        return "husky"
    for manager, names in MANAGER_FILES.items():
        if any((top / n).is_file() for n in names):
            return manager
    for manager in ("lefthook", "pre-commit"):
        needle = manager if manager != "pre-commit" else "generated by pre-commit"
        if any(needle in t.lower() for t in hook_texts.values()):
            return manager
    return None


def state(repo=None) -> dict:
    """Everything :func:`install` needs to decide, read fresh from git: the
    effective hooks dir, who put ``core.hooksPath`` there and at what scope,
    whether that dir is shared outside this checkout, which hook manager (if
    any) owns the hook files, and each hook's own existence/ownership/wiring.
    """
    repo = Path(repo) if repo else Path.cwd()
    hooks_dir = _hooks_dir(repo)
    scope, hooks_path_value = _hooks_path_scope(repo)
    common_dir = _abs_path(repo, "--git-common-dir")
    top_level = _abs_path(repo, "--show-toplevel")
    shared = scope in ("global", "system") or not _within(hooks_dir, common_dir, top_level)

    hooks: dict[str, dict] = {}
    texts: dict[str, str] = {}
    for name in GIT_HOOKS:
        path = hooks_dir / name
        exists = path.is_file()
        text = ""
        if exists:
            try:
                text = path.read_text(encoding="utf-8", errors="replace")
            except OSError:
                text = ""
        texts[name] = text
        hooks[name] = {
            "path": path,
            "exists": exists,
            "ours": GIT_HOOK_MARK in text,
            "wired": HOOK_TRIGGER[name] in text,
        }

    manager = _detect_manager(top_level, hooks_path_value, texts)
    return {
        "hooks_dir": hooks_dir,
        "hooks_path_value": hooks_path_value,
        "hooks_path_scope": scope,
        "shared": shared,
        "manager": manager,
        "hooks": hooks,
    }


# --- writing (or not) --------------------------------------------------------------

def _lines_to_add(name: str) -> str:
    body = GIT_HOOKS[name].split("\n", 1)[1]
    return "".join(f"    {ln}\n" for ln in body.splitlines())


def _wired_line(name: str, path: Path, scope: str | None = None) -> str:
    tail = f" (shared hooks dir, scope {scope})" if scope else ""
    return f"{name}: already wired through {path}{tail}"


def _manager_snippet(manager: str, name: str) -> str:
    trigger = HOOK_TRIGGER[name]
    if manager == "husky":
        return (f"{name}: husky detected - add to .husky/{name}:\n"
                f"    command -v shapa >/dev/null 2>&1 && {trigger}"
                + (" ; [ $? -eq 1 ] && exit 1\n" if name == "pre-commit" else " 2>/dev/null\n"))
    if manager == "lefthook":
        stage = name  # lefthook.yml stage keys match git's hook names
        return (f"{name}: lefthook detected - add to lefthook.yml:\n"
                f"    {stage}:\n      commands:\n        shapa:\n          run: {trigger}\n")
    # pre-commit framework
    stages = "" if name == "pre-commit" else "\n          stages: [post-commit]"
    return (f"{name}: pre-commit framework detected - add to .pre-commit-config.yaml:\n"
            "    - repo: local\n      hooks:\n        - id: shapa-ledger-" + name + "\n"
            f"          name: {trigger}\n          entry: {trigger}\n"
            f"          language: system\n          pass_filenames: false{stages}\n")


def install(repo=None) -> list[str]:
    """Write shapa's git hooks into *repo*'s hooks dir, never where they
    would clobber a shared dir, a hook manager's own file, or a foreign
    hand-written hook. One report line (sometimes multi-line) per hook."""
    repo = Path(repo) if repo else Path.cwd()
    st = state(repo)
    out: list[str] = []
    for name in GIT_HOOKS:
        h = st["hooks"][name]
        path = h["path"]
        if st["shared"]:
            if h["wired"]:
                out.append(_wired_line(name, path, st["hooks_path_scope"]))
            else:
                out.append(f"{name}: {path} is a shared hooks dir used by every repo on this "
                           f"machine (core.hooksPath, scope {st['hooks_path_scope']}) - add by "
                           "hand:\n" + _lines_to_add(name))
            continue
        if st["manager"]:
            out.append(_wired_line(name, path) if h["wired"] else _manager_snippet(st["manager"], name))
            continue
        if h["exists"] and not h["ours"]:
            out.append(_wired_line(name, path) if h["wired"] else
                        f"{name}: {path} exists and is not shapa's - add before its final "
                        "exit:\n" + _lines_to_add(name))
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(GIT_HOOKS[name], encoding="utf-8")
        path.chmod(0o755)
        out.append(f"{name}: {path}")
    return out
